---
- name: install system dependencies.
  become:        yes
  become_method: sudo
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - git
    - python3-pip
    - python3-pil
    - screen
    - htop
    - jq
    - python3-systemd

- name: download pip packages.
  become:        yes
  become_method: sudo
  pip: >
    name={{ item }}
    executable='/usr/bin/pip3'
  with_items:
    - numpy
    - sh
    - docopt
    - prompter

- name: set the timezone
  shell: timedatectl set-timezone Europe/Dublin

- name:  install large file storage
  shell: "curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash"

- name: install git-lfs
  become:        yes
  become_method: sudo
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - git-lfs
