---
- name: download polynomial from github package.
  become: no
  git: >
    repo="https://github.com/rgrannell1/polynomial.git"
    dest="tasks/{{start_time}}/repo"

- name: create build directories.
  file: >
    path={{ item }}
    state=directory
    mode=0755
  with_items:
    - 'root/archives'
    - '{{ task_path }}/output'
    - '{{ task_path }}'
    - '{{ task_path }}/output/json'
    - '{{ task_path }}/output/images'
    - '{{ task_path }}/python'
    - '{{ task_path }}/python/commons'

- name: copy argument file specifying which roots to generate / draw.
  template: >
    src=arguments.py
    dest='{{ task_path }}/arguments.py'

- name: copy python template files
  template: >
    src={{ item }}
    dest={{ task_path }}/{{ item }}
  with_items:
    - python/commons/colours.py
    - python/commons/constants.py
    - python/commons/utils.py
    - python/__init__.py

    - python/copy_images.py
    - python/draw_solutions.py
    - python/render_pixels.py
    - python/solve_polynomials.py
    - python/run_foo.py

- name: symlink the task to the alias 'current'
  file: >
    src={{task_path}}
    dest=/root/tasks/current
    state=link
