---
- name: download polynomial from github package.
  become: no
  git: >
    repo="https://github.com/rgrannell1/polynomial.git"
    dest="{{repo_path}}"

- name: create build directories.
  shell: mkdir -p {{ item }}
  with_items:
    - 'archives'
    - '{{ task_path }}'
    - '{{ task_path }}/output'
    - '{{ task_path }}/output/json'
    - '{{ task_path }}/output/images'
    - '{{ task_path }}/python'
    - '{{ task_path }}/python/commons'

- name: copy argument file specifying which roots to generate / draw.
  template: >
    src=arguments.py
    dest='{{ task_path }}/arguments.py'

- name: symlink the task to the alias 'current'
  file: >
    src={{task_path}}
    dest={{local_home}}/tasks/current
    state=link
