---
- name: download polynomial from github package.
  become: no
  git: >
    repo="https://github.com/rgrannell1/polynomial.git"
    dest="tasks/{{start_time}}/repo"

- name: copy python files to /bin.
  command: >
    cp tasks/{{start_time}}/repo/src/python/{{ item }}.py /bin/{{item}}
  with_items:
    - render-pixels
    - draw-solutions
    - solve-polynomials

- name: create build directories.
  file: >
    path={{ item }}
    state=directory
    mode=0755
  with_items:
    - '{{ repo_path }}/output'
    - '{{ task_path }}/jobs'
    - '{{ repo_path }}/output/json'
    - '{{ repo_path }}/output/images'

- name: copy argument specifying which roots to generate / draw.
  template: >
    src=jobs/{{item}}
    dest='{{ task_path }}/jobs'
  with_items:
    - arguments.py

- name: symlink
  file: >
    src={{task_path}}
    dest=/root/tasks/current
    state=link
