---
- name: copy source code to build folder
  become: no
  copy: >
    src="{{project_root}}/src"
    dest="{{repo_path}}"
  when: inventory_hostname == "localhost"

- name: download polynomial from github package.
  become: no
  git: >
    repo="https://github.com/rgrannell1/polynomial.git"
    dest="{{repo_path}}"
  when: inventory_hostname != "localhost"

- name: create build directories.
  shell: mkdir -p {{ item }}
  with_items:
    - '{{ task_path }}'

- name: copy argument file specifying which roots to generate / draw.
  template: >
    src=arguments.py
    dest='{{ task_path }}/arguments.py'

- name: symlink the task to the alias 'current'
  file: >
    src={{task_path}}
    dest={{local_home}}/tasks/current
    state=link
