---
- name: download polynomial from github package.
  become: no
  git: >
    repo="https://github.com/rgrannell1/polynomial.git"
    dest="tasks/{{start_time}}/repo"

- name: copy python files to /bin.
  command: >
    cp tasks/{{start_time}}/repo/src/python/{{ item }}.py /bin/{{item}}
  with_items:
    - render-pixels
    - draw-solutions
    - solve-polynomials

- name: create build directories.
  file: >
    path={{ item }}
    state=directory
    mode=0755
  with_items:
    - '{{ repo_path }}/output'
    - '{{ task_path }}/jobs'
    - '{{ repo_path }}/output/json'
    - '{{ repo_path }}/output/images'

- name: copy argument specifying which roots to generate / draw.
  template: >
    src=jobs/arguments.py
    dest='{{ task_path }}/arguments.py'

- name: symlink the task to the alias 'current'
  file: >
    src={{task_path}}
    dest=/root/tasks/current
    state=link

- name: copy role files
  template: >
    src={{item}}
    dest={{task_path}}/{{item}}
  with_items:
    - run.py
    - copy-images.py
    - symlink-matching-data.py

#- name: symlink data files, when allowed.
#  shell: "python3 {{task_path}}/symlink-matching-data.py"
