---

- name: commit the newly created images.
  shell: "cd {{local_home}}/polynomial-images/ ; git add -A . ; git commit -am 'committing fetched image' ; git push"

- name: 'set up polynomial-images output-repo'
  git:
    repo:   'https://github.com/rgrannell1/polynomial-images.git'
    dest:   "{{local_home}}/polynomial-images"
    update: yes
    clone:  yes
    force:  no

- name: wait for the file to be created
  wait_for: >
    path="{{local_home}}/tasks/current/output/final_image.png"

- name: copy images back to the local machine.
  fetch: >
    src="{{local_home}}/tasks/current/output/final_image.png"
    dest="{{local_home}}/polynomial-images/{{start_time}}.png"
    flat=yes

- name: copy image to foo
  shell: "cp {{local_home}}/tasks/current/output/final_image.png {{local_home}}/polynomial-images/{{start_time}}.png"

- name: set up git large-file storage.
  shell: "cd {{local_home}}/polynomial-images/; git lfs track *.png"

- name: commit the newly created image.
  shell: "cd {{local_home}}/polynomial-images/ ; git add -A . ; git commit -am 'committing fetched image' ; git push"
