---
- name: install system dependencies.
  become:        yes
  become_method: sudo
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - git
    - python3-pip
    - python3-pil
    - screen
    - htop
    - jq

- name: download pip packages.
  become:        yes
  become_method: sudo
  pip: >
    name={{ item }}
    executable='/usr/bin/pip3'
  with_items:
    - numpy
    - sh
    - docopt
    - prompter

- name: set the timezone
  shell: timedatectl set-timezone Europe/Dublin
