---
- name: system dependencies
  become:        yes
  become_method: sudo
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - cowsay
    - git
    - python3-pip
    - python3-pil
    - screen

- name: pip packages
  become:        yes
  become_method: sudo
  pip: >
    name={{ item }}
    executable='/usr/bin/pip3'
  with_items:
    - numpy
    - docopt
    - prompter

- name: github package
  become: no
  git: >
    repo="https://github.com/rgrannell1/polynomial.git"
    dest={{ repo_path }}

- name: create an output directory
  file: >
    path={{ item }}
    state=directory
    mode=0755
  with_items:
    - '{{ repo_path }}/output'
    - '{{ repo_path }}/output/json'
    - '{{ repo_path }}/output/images'
