---
#- name: system dependencies
#  become:        yes
#  become_method: sudo
#  apt: >
#    name={{ item }}
#    state=present
#    update_cache=yes
#  with_items:
#    - git
#    - python3-pip
#    - python3-pil
#    - screen
#
#- name: pip packages
#  become:        yes
#  become_method: sudo
#  pip: >
#    name={{ item }}
#    executable='/usr/bin/pip3'
#  with_items:
#    - numpy
#    - sh
#    - docopt
#    - prompter

- name: download github package
  become: no
  git: >
    repo="https://github.com/rgrannell1/polynomial.git"
    dest="tasks/{{start_time}}/repo"

- name: copy python files to /bin
  command: >
    cp tasks/{{start_time}}/repo/src/python/cli/{{ item }}.py /bin/{{item}}
  with_items:
    - render-pixels
    - draw-solutions
    - solve-polynomials

- name: create an output directory
  file: >
    path={{ item }}
    state=directory
    mode=0755
  with_items:
    - '{{ repo_path }}/output'
    - '{{ repo_path }}/output/json'
    - '{{ repo_path }}/output/images'
